### PR TITLE
make CLDF markdown rendering work

### PR DESCRIPTION
**Pull request by xrotwang**

### CODE REVIEW

**Comment by xrotwang** [comment]
@davidainman sorry for confusing you with the `with_internal_ref_link` stuff which was not relevant for the usage here - together with `clld-markdown-plugin`. I now released a new version of this plugin which can also handle "local" or "partial" reference lists.

**Comment by davidainman** [comment]
This looks great and I can confirm it works. Merging the pull request. Two questions:

1. I still can't get the link to the Parameters page working. Currently this is just on Lat.01, which is linked as (ParameterTable#cldf:Lat-01) -- this doesn't go where I expect it to. Is there another way to format this?
2. The references are being listed exactly as they appear in the bib file (which is slightly inconsistent, see "Lev Michael and Chang, Will and Tammy Stark"). We can fix the authors systematically in the bib, but is there a way to render the title in italics, as in Grambank e.g. https://grambank.clld.org/parameters/GB020#2/21.0/151.9 ? Or is this list in Grambank something that was generated manually?

**Review by davidainman — COMMENTED** [review]
Changes look good, see comment in conversation for issues.

**Comment by xrotwang** [comment]
Re. the format of the reference list: The formatting of the Grambank feature descriptions is indeed done manually, see https://github.com/grambank/grambank/wiki/GB020#references . In fact, Grambank doesn't use CLDF Markdown at all - you are the pioneer, here :)

It should be possible to do what you want here, though
https://github.com/clld/clld-markdown-plugin/blob/f899e2409c151443260f7a43497f335c89cd053c/src/clld_markdown_plugin/__init__.py#L147
I'll have a go in a minute.

**Comment by xrotwang** [comment]
Ad 1.: We are talking about the following snippet in `laterals.md`:
```
### [Lat.01 Does the language have a lateral approximant phoneme /l/ or an allophone \[l\] and if so, with what other allophones does this /l/ or \[l\] alternate?](ParameterTable#cldf:Lat-01)
  **{ laterals or glides | rhotic | n or d | n or d and rhotic | no }**
```
correct?

And what you want is a link to the parameter page for `Lat-01`, using the parameter question as link label?

`clld-markdown-plugin` allows specifying custom renderer function for particular object types. So one could write one for parameters, which not only creates the link but also lists the allowed codes/states - possible with number of matching languages. Would this be an option?

**Comment by xrotwang** [comment]
@davidainman see https://github.com/PaprikaSteiger/ooaclld/pull/13

**Comment by xrotwang** [comment]
Also, after upgrading to clld-markdown-plugin 0.4 you should see the references listed with volume titles in italics.

**Comment by davidainman** [comment]
So far not seeing this behavior.

**Comment by xrotwang** [comment]
Screenshot 2023-12-08 at 11-33-10 None - Feature Set Laterals

```
$ pip freeze | grep clld
clld==10.0.0
clld-glottologfamily-plugin==4.0.0
-e git+https://github.com/clld/clld-markdown-plugin@ea434d4f68a2294b4c2c01f0d054128a3a20fb7b#egg=clld_markdown_plugin
clldmpg==4.3.0
clldutils==3.21.0
```

**Comment by davidainman** [comment]
It was clldutils, thank you!

**Pull request merged**
