### PR TITLE
Dinman branch

### PR DESCRIPTION
**Pull request by davidainman**
For some reason, the references are not rendering on the new feature description (at contributions/MonPl). Have I missed something in this process, @xrotwang?

### CODE REVIEW

**Comment by xrotwang** [comment]
```
$ pip freeze
appdirs==1.4.4
arrow==1.3.0
attrs==22.2.0
Babel==2.12.1
beautifulsoup4==4.11.2
bs4==0.0.1
certifi==2022.12.7
charset-normalizer==3.1.0
cldfbench==1.14.0
cldfcatalog==1.5.1
-e git+https://github.com/cldf/cldfviz@f6763f321396d6f44724fb5369ef9a0f7a310cbc#egg=cldfviz
cldfzenodo==1.1.0
clld==10.0.0
clld-glottologfamily-plugin==4.0.0
-e git+https://github.com/clld/clld-markdown-plugin@ea434d4f68a2294b4c2c01f0d054128a3a20fb7b#egg=clld_markdown_plugin
clldmpg==4.3.0
clldutils==3.21.0
colorama==0.4.6
colorlog==6.7.0
commonnexus==1.9.2
contourpy==1.2.0
csvw==3.1.3
custom-inherit==2.4.1
cycler==0.12.1
exceptiongroup==1.2.0
fonttools==4.46.0
future==0.18.3
gitdb==4.0.10
GitPython==3.1.31
greenlet==2.0.2
html5lib==1.1
hupper==1.11
idna==3.4
iniconfig==2.0.0
isodate==0.6.1
Jinja2==3.1.2
jmespath==1.0.1
jsonschema==4.17.3
kiwisolver==1.4.5
language-tags==1.2.0
latexcodec==2.0.1
linglit==1.3.0
lxml==4.9.2
Mako==1.2.4
Markdown==3.4.1
MarkupSafe==2.1.2
matplotlib==3.8.2
multipledispatch==1.0.0
nameparser==1.1.2
newick==1.8.1
numpy==1.26.2
-e git+https://github.com/PaprikaSteiger/ooaclld@244097b1f2b21063c154c6d6e4c2f21a811f3b0c#egg=ooaclld&subdirectory=ooaclld
packaging==23.2
PasteDeploy==3.0.1
Pillow==10.1.0
plaster==1.1.2
plaster-pastedeploy==1.0.1
pluggy==1.3.0
purl==1.6
pybtex==0.24.0
pycldf==1.36.0
pycountry==22.3.5
pyglottolog==3.11.0
Pygments==2.14.0
pyigt==2.0.0
pylatexenc==2.10
pyparsing==3.0.9
pypng==0.20220715.0
pyramid==2.0.1
pyramid-debugtoolbar==4.10
pyramid-mako==1.1.0
pyramid-tm==2.5
pyrsistent==0.19.3
pytest==7.4.3
python-dateutil==2.8.2
python-frontmatter==1.0.0
python-nexus==2.9.0
PyYAML==6.0
rdflib==6.2.0
regex==2022.10.31
reportlab==4.0.7
requests==2.28.2
rfc3986==1.5.0
segments==2.2.1
six==1.16.0
smmap==5.0.0
soupsieve==2.4
SQLAlchemy==1.4.46
tabulate==0.9.0
termcolor==2.2.0
TexSoup==0.3.1
thefuzz==0.19.0
tomli==2.0.1
toyplot==1.0.3
toytree==2.0.1
tqdm==4.65.0
transaction==3.0.1
translationstring==1.4
types-python-dateutil==2.8.19.14
Unidecode==1.3.6
uritemplate==4.1.1
urllib3==1.26.14
venusian==3.0.0
waitress==2.1.2
webassets==2.0
webencodings==0.5.1
WebOb==1.8.7
Whoosh==2.7.4
zenodoclient==0.5.1
zope.deprecation==4.4.0
zope.interface==5.5.2
zope.sqlalchemy==2.0
```

**Comment by xrotwang** [comment]
Screenshot 2023-12-11 at 19-56-52 None - Feature Set Monoexponential Verbal Plurals

**Comment by davidainman** [comment]
Writing this comment partially to myself for tomorrow.

At least locally, the cause was one of the sources (tarpent1983morphophonemics). When I tried to access sources/tarpent1983morphophonemics, I get an internal server error, and removing this source from the .md file allowed the references to render.

Trial and error determined that it was a lack of page numbers in the source. Adding page numbers allowed both the references section and the sources page to be rendered. Presumably some difference in Robert and my packages is causing this, but is it possible that CLLD (or some dependent package) is expecting page numbers on all articles?

More to investigate tomorrow.

**Comment by davidainman** [comment]
annotated-types==0.6.0
appdirs==1.4.4
arrow==1.3.0
attrs==22.1.0
Babel==2.13.0
beautifulsoup4==4.12.2
bibtexparser==2.0.0b4
binaryornot==0.4.4
blosc2==2.0.0
bs4==0.0.1
cachetools==5.3.1
Cartopy==0.21.1
certifi==2023.7.22
chardet==5.2.0
charset-normalizer==3.3.0
cldfbench==1.14.0
cldfcatalog==1.5.1
cldfviz==1.0.2
cldfzenodo==1.1.0
click==8.1.7
click-plugins==1.1.1
cligj==0.7.2
clld==11.0.1
clld-glottologfamily-plugin==4.0.0
clld-markdown-plugin==0.4.0
clldmpg==4.3.0
clldutils==3.22.0
colorama==0.4.6
colorlog==6.7.0
commonnexus==1.7.0
contourpy==1.1.1
cookiecutter==2.4.0
csvw==3.1.3
custom-inherit==2.4.1
cycler==0.12.1
Cython==3.0.5
descartes==1.1.0
et-xmlfile==1.1.0
exceptiongroup==1.2.0
fiona==1.9.5
flake8==6.1.0
fonttools==4.45.0
future==0.18.3
geopandas==0.13.2
gitdb==4.0.10
GitPython==3.1.40
google-api-core==2.12.0
google-api-python-client==2.104.0
google-auth==2.23.3
google-auth-httplib2==0.1.1
googleapis-common-protos==1.61.0
greenlet==3.0.0
html5lib==1.1
httplib2==0.22.0
hupper==1.12
idna==3.4
importlib-metadata==6.8.0
importlib-resources==6.1.0
iniconfig==2.0.0
isodate==0.6.1
Jinja2==3.1.2
jmespath==1.0.1
jsonschema==4.17.3
jsonschema-specifications==2023.7.1
kiwisolver==1.4.5
language-tags==1.2.0
latexcodec==2.0.1
linglit==1.4.0
llvmlite==0.41.1
lxml==4.9.3
Mako==1.2.4
Markdown==3.5
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.7.4
mccabe==0.7.0
mdurl==0.1.2
msgpack==1.0.7
multipledispatch==1.0.0
nameparser==1.1.3
newick==1.9.0
numba==0.58.1
numexpr==2.8.6
numpy==1.24.4
-e git+https://github.com/PaprikaSteiger/ooaclld.git@244097b1f2b21063c154c6d6e4c2f21a811f3b0c#egg=ooaclld&subdirectory=ooaclld
openpyxl==3.0.10
packaging==23.2
pandas==1.4.4
PasteDeploy==3.0.1
Pillow==10.1.0
pkgutil_resolve_name==1.3.10
plaster==1.1.2
plaster-pastedeploy==1.0.1
pluggy==1.3.0
protobuf==4.24.2
psutil==5.9.6
purl==1.6
py-cpuinfo==9.0.0
pyasn1==0.5.0
pyasn1-modules==0.3.0
pybtex==0.24.0
pycldf==1.36.0
pycodestyle==2.11.1
pycountry==22.3.5
pydantic==2.5.1
pydantic_core==2.14.3
pyflakes==3.1.0
pygeos==0.14
pyglottolog==3.12.0
Pygments==2.16.1
pyigt==2.0.0
pylatexenc==2.10
pyparsing==3.1.1
pypng==0.20220715.0
pyproj==3.5.0
pyramid==2.0.2
pyramid-debugtoolbar==4.10
pyramid-mako==1.1.0
pyramid-tm==2.5
pyrsistent==0.19.3
pyshp==2.3.1
pytest==7.4.3
python-dateutil==2.8.2
python-frontmatter==1.0.0
python-slugify==8.0.1
pytz==2023.3.post1
PyYAML==6.0.1
rapidfuzz==3.4.0
rdflib==7.0.0
referencing==0.30.2
regex==2023.10.3
reportlab==4.0.7
requests==2.31.0
rfc3986==1.5.0
rich==13.6.0
rpds-py==0.10.6
rsa==4.9
ruamel.yaml==0.18.5
ruamel.yaml.clib==0.2.8
sbayes @ file:///Users/david/Documents/GitHub/sBayes
scipy==1.10.1
seaborn==0.13.0
segments==2.2.1
shapely==2.0.2
six==1.16.0
smmap==5.0.1
soupsieve==2.5
SQLAlchemy==1.4.49
tables==3.8.0
tabulate==0.9.0
termcolor==2.3.0
TexSoup==0.3.1
text-unidecode==1.3
thefuzz==0.20.0
tomli==2.0.1
toyplot==1.0.3
toytree==2.0.1
tqdm==4.64.1
transaction==3.1.0
translationstring==1.4
types-python-dateutil==2.8.19.14
typing_extensions==4.8.0
tzdata==2023.3
Unidecode==1.3.7
uritemplate==4.1.1
urllib3==2.0.7
venusian==3.0.0
waitress==2.1.2
webassets==2.0
webencodings==0.5.1
WebOb==1.8.7
Whoosh==2.7.4
zenodoclient==0.5.1
zipp==3.17.0
zope.deprecation==5.0
zope.interface==6.1
zope.sqlalchemy==3.1

**Comment by xrotwang** [comment]
Ah, can confirm. It seems I introduced this regression in clldutils 3.22.0. Will check and fix tomorrow.

**Comment by xrotwang** [comment]
See https://github.com/clld/clldutils/issues/110

**Comment by xrotwang** [comment]
Ok, clldutils 3.22.1 should fix this problem.

**Comment by davidainman** [comment]
Can confirm, great!

**Pull request merged**
